name: Inventory Scraper

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Fetch Inventory Data
      run: |-
        curl https://shop.lululemon.com/api/shipinventory/?skus\=113275232\&productId\=prod9610199 | jq . > surge_xs_blk.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(env TZ=":US/Eastern" date)
        git commit -m "Latest update: ${timestamp}" || exit 0
        git push
